apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web
spec:
  containers:
  - name: nginx
    image: vials/test:latest
  initContainers:
  - name: init-test
    image: busybox:1.31.0
    command: ['sh', '-c', 'mkdir /app && wget -O- https://tinyurl.com/otus-k8s-intro | sh']
